### ISSUE TITLE
How to add this plugin

### ISSUE THREAD

**Issue by Asterovim** [eirabben/tree-sitter-twig#1]
Hello.

Could you please explain how to use it ? I would like to have syntax color twig + html with treesitter.

I have try https://github.com/nvim-treesitter/nvim-treesitter#adding-parsers

```
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.twig = {
  install_info = {
    url = "https://github.com/eirabben/tree-sitter-twig", -- local path or git repo
    files = {"src/parser.c"},
    -- optional entries:
    branch = "main", -- default branch in case of git repo if different from master
    generate_requires_npm = false, -- if stand-alone parser without npm dependencies
    requires_generate_from_grammar = false, -- if folder contains pre-generated src/parser.c
  },
  filetype = "twig", -- if filetype does not match the parser name
}
```
`:TSInstall twig`

i didn't see any change into twig file :(

Can you help me please ?

**Comment by eirabben** [comment]
Hi

To make this work with nvim-treesitter, you would have to add the files from the queries folder to your vim configuration: https://github.com/nvim-treesitter/nvim-treesitter#adding-queries. The queries in this version of the parser do not work with nvim-treesitter, because nvim-treesitter does not support combined injections yet. See the issue here for more info: https://github.com/nvim-treesitter/nvim-treesitter/issues/1998.

I will try to add some documentation with a guide on nvim-treesitter integration.

Please note that this project is in very early development, and only highlights start and end blocks in Twig. I am currently working on extending the HTML parser, so we can get full highlighting and indentations.

**Comment by Asterovim** [comment]
Thanks you, i will wait next update. If you need beta tester and help im here ;)

**Comment by eirabben** [comment]
@Asterovim The plugin now directly extends the HTML grammar, so you get highlights for the HTML. I have also added a readme with instructions on how to use it with nvim-treesitter. 

Currently there is no highlights for code inside Twig tags, but I'm working on that now. When Twig highlighting is working, I will request for this plugin to be added to the nvim-treesitter list.

**Comment by boonkerz** [comment]
Currently Status for twig?
